---
- name: Installation du service Web de test
  hosts: windows
  tasks:
    - name: Installer le role IIS
      win_feature:
        name: Web-Server
        state: present
        include_management_tools: yes

    - name: Demarrer le service IIS
      win_service:
        name: W3SVC
        state: started
        start_mode: auto